### ISSUE TITLE
kroupa IMF bug

### ISSUE THREAD

**Issue by Szimcha** [keflavich/imf#2]
Dear Adam, the "kroupa" IMF seems the have a bug. When using inverse_imf or make_cluster only 120 Msun stars are produced.  When using e.g. "salpeter" it seems to work fine. 
Thanks, Josefa

**Comment by keflavich** [comment]
Thanks.  I believe I've fixed the bug in f70d189, but I'd like to implement some tests before I mark this as resolved.  Try downloading the latest version and see if it does what you expect.

**Comment by Szimcha** [comment]
Hi Adam, thanks a lot for fixing the bug. Yes, it seems to work fine now when using the kroupa IMF. Josefa
