### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by robelgeda** [keflavich/imf#22]
Hi all,
I am using this library for one of my projects and need to keep track of the version I am using. I see that there has only been one release of this code in May 13 2020. Are there plans to make another release soon? 

Thank you.

**Comment by keflavich** [comment]
I could cut a release another release now; is the current dev version what you're using?  I'd recommend tagging a specific git commit anyway, though, as there's no particular release schedule.

**Comment by robelgeda** [comment]
Thank you! I think we have some time before we need a release. I was hoping to have this for the long term so no need to rush. If anything I will point to a commit if needed.

**Comment by keflavich** [comment]
New release as of today to solve #23, so I'm closing this.
