### ISSUE TITLE
Migrating from travis CI to github actions

### ISSUE THREAD

**Issue by segasai** [keflavich/imf#24]
As travis about to retire for open source projects, it is probably a good idea to move to github actions. 
It is pretty straightforward and for example can be done with a single file like that
https://github.com/segasai/minimint/blob/master/.github/workflows/test.yml

(it would be also nice if the CI status was successful, rather than failed as it is now since the last commit).

**Comment by keflavich** [comment]
Yeah, when I next have time, I'd love to get all my repos onto gh actions for CI.  That's not in the foreseeable future, though, so I welcome any PRs.  @segasai I'd also be happy to give you maintainer permissions on this repo if you want to help out.

**Comment by segasai** [comment]
Yes please, if you give me permissions, I may do it.

**Comment by keflavich** [comment]
OK you have access now as a collaborator.  Apparently that's as fine-grained as the permission settings go... I thought there were other controls, but I can't find them, so lmk if you're able to muck with actions.

**Comment by segasai** [comment]
Yes, thanks. I think, since I can create files in the repo, I'll be able to enable actions.
